from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from database import get_db, supabase
from models import User, Profile
from pydantic import BaseModel, EmailStr
from typing import List, Optional
import uuid

router = APIRouter(prefix="/profile", tags=["Profile"])

# --- Schemas ---

class PortfolioItem(BaseModel):
    title: str
    url: str
    description: str

class SignupRequest(BaseModel):
    email: EmailStr
    password: str
    name: str

class ProfileCreate(BaseModel):
    skills: List[str]
    niche: str
    experience_level: str
    preferred_rate_min: int
    preferred_rate_max: int
    preferred_job_type: str
    preferred_job_size: str
    writing_samples: Optional[str] = None
    portfolio: Optional[List[PortfolioItem]] = []
    keywords_include: Optional[List[str]] = []
    keywords_exclude: Optional[List[str]] = []

class LoginRequest(BaseModel):
    email: EmailStr
    password: str

# --- Endpoints ---

@router.post("/signup")
def signup(data: SignupRequest, db: Session = Depends(get_db)):

    # Step 1: Create auth user in Supabase
    auth_response = supabase.auth.admin.create_user({
        "email": data.email,
        "password": data.password,
        "email_confirm": True   # skip email verification for now
    })

    if not auth_response.user:
        raise HTTPException(status_code=400, detail="Signup failed")

    # Step 2: Create user in our DB with same ID as Supabase auth
    new_user = User(
        id=uuid.UUID(auth_response.user.id),
        email=data.email,
        name=data.name
    )
    db.add(new_user)
    db.commit()
    db.refresh(new_user)

    return {
        "message": "Account created successfully",
        "user_id": str(new_user.id)
    }


@router.post("/login")
def login(data: LoginRequest):

    auth_response = supabase.auth.sign_in_with_password({
        "email": data.email,
        "password": data.password
    })

    if not auth_response.user:
        raise HTTPException(status_code=401, detail="Invalid credentials")

    return {
        "message": "Login successful",
        "user_id": str(auth_response.user.id),
        "access_token": auth_response.session.access_token
    }


@router.post("/create/{user_id}")
def create_profile(user_id: str, data: ProfileCreate, db: Session = Depends(get_db)):

    # Check user exists
    user = db.query(User).filter(User.id == uuid.UUID(user_id)).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    # Check profile doesn't already exist
    existing = db.query(Profile).filter(Profile.user_id == uuid.UUID(user_id)).first()
    if existing:
        raise HTTPException(status_code=400, detail="Profile already exists")

    new_profile = Profile(
        user_id=uuid.UUID(user_id),
        skills=data.skills,
        niche=data.niche,
        experience_level=data.experience_level,
        preferred_rate_min=data.preferred_rate_min,
        preferred_rate_max=data.preferred_rate_max,
        preferred_job_type=data.preferred_job_type,
        preferred_job_size=data.preferred_job_size,
        writing_samples=data.writing_samples,
        tone_summary=None,          # will be generated by AI after profile creation
        portfolio=[item.dict() for item in data.portfolio],
        keywords_include=data.keywords_include,
        keywords_exclude=data.keywords_exclude
    )
    db.add(new_profile)
    db.commit()

    return {
        "message": "Profile created successfully",
        "runs_remaining": 3
    }


@router.get("/{user_id}")
def get_profile(user_id: str, db: Session = Depends(get_db)):

    user = db.query(User).filter(User.id == uuid.UUID(user_id)).first()
    if not user:
        raise HTTPException(status_code=404, detail="User not found")

    profile = db.query(Profile).filter(Profile.user_id == uuid.UUID(user_id)).first()
    if not profile:
        raise HTTPException(status_code=404, detail="Profile not found")

    return {
        "name": user.name,
        "email": user.email,
        "skills": profile.skills,
        "niche": profile.niche,
        "experience_level": profile.experience_level,
        "preferred_rate_min": profile.preferred_rate_min,
        "preferred_rate_max": profile.preferred_rate_max,
        "preferred_job_type": profile.preferred_job_type,
        "portfolio": profile.portfolio,
        "runs_used": profile.runs_used,
        "runs_remaining": profile.runs_limit - profile.runs_used,
        "is_active": profile.is_active
    }